name: mtk2garmin-converter docker image

on:
  push:
    paths: 
      - 'mtk2garmin-converter/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: mtk2garmin-converter
        tags: teemupel/mtk2garmin-converter:latest
