name: mtk2garmin-converter docker image

on:
  workflow_dispatch:
  push:
    paths: 
      - 'mtk2garmin-converter/**'
      - '.github/workflows/dockerimage.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:mtk2garmin-converter"
          tags: teemupel/mtk2garmin-converter:latest
